- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: {{ SUBLIME_INSTALL_DIR }}
    state: directory
    mode: '0755'

- name: Extract sublime_text tar.xz into SUBLIME_INSTALL_DIR
  ansible.builtin.unarchive:
    src: '{{ DOWNLOADS }}/sublime_text_build_4113_x64.tar.xz'
    dest: '{{ SUBLIME_INSTALL_DIR }}'

- name: Make sublime easy to access from any terminal
  ansible.builtin.unarchive:
    src: '{{ SUBLIME_INSTALL_DIR }}/sublime_text/sublime_text'
    dest: '/usr/local/bin/sbl'

- name: Create Sublime Desktop 
  template:
    src: templates/sublime_text.desktop.j2
    dest: /usr/share/applications/sublime_text.desktop

- name: Show user installation completed successfully
  copy:
    src: files/install_sublime_thankyou.html
    dest: /tmp/install_sublime_thankyou.html
  command: 'firefox "/tmp/install_sublime_thankyou.html"'
