- name: task1 in role2 without vars  - role1_task_vars overrides role1_vars_main_applied overrides playbook_play_vars overrides group_vars, - role1_task_vars also overrides all of role2_task_vars and below
  debug: 
    msg: 
     - 'Inside role2 in task1 favcolor - {{ favcolor }}'
     - 'Inside role2 in task1 inventories_main_vars - {{ inventories_main_vars }}'
     - 'Inside role2 in task1 group_vars - {{ group_vars }}'
     - 'Inside role2 in task1 playbook_play1_vars - {{ playbook_play1_vars }}'
     - 'Inside role2 in task1 role1_defaults_main - {{ role1_defaults_main }}'
     - 'Inside role2 in task1 role1_library_main - {{ role1_library_main }}'
     - 'Inside role2 in task1 role1_task_vars - {{ role1_task_vars }}'
     - 'Inside role2 in task1 role1_vars_main - {{ role1_vars_main }}'
     - 'Inside role2 in task1 role2_defaults_main - {{ role2_defaults_main }}'
     - 'Inside role2 in task1 role2_vars_main - {{ role2_vars_main }}'
     - 'Inside role2 in task1 role2_library_main - {{ role2_library_main }}'
     - 'Inside role2 in task1 role2_task_vars - {{ role2_task_vars }}'
     
     

- name: task2 in role2 with vars  - role1_task_vars overrides role1_vars_main_applied overrides playbook_play_vars overrides group_vars, - role1_task_vars also overrides all of role2_task_vars and below
  vars:
    favcolor: 'role2_task2_vars_applied'
    
    inventories_main_vars: 'role2_task2_vars_applied'
    group_vars: 'role2_task2_vars_applied'
    playbook_play1_vars: 'role2_task2_vars_applied'

    role1_defaults_main: 'role2_task2_vars_applied'
    role1_vars_main: 'role2_task2_vars_applied'
    role1_library_main: 'role2_task2_vars_applied'
    role1_task_vars: 'role2_task2_vars_applied'

    role2_defaults_main: 'role2_task2_vars_applied'
    role2_vars_main: 'role2_task2_vars_applied'
    role2_library_main: 'role2_task2_vars_applied'
    role2_task_vars: 'role2_task2_vars_applied'

  debug: 
    msg: 
     - 'Inside role2 in task2 favcolor - {{ favcolor }}'
     - 'Inside role2 in task2 inventories_main_vars - {{ inventories_main_vars }}'
     - 'Inside role2 in task2 group_vars - {{ group_vars }}'
     - 'Inside role2 in task2 playbook_play1_vars - {{ playbook_play1_vars }}'
     - 'Inside role2 in task2 role1_defaults_main - {{ role1_defaults_main }}'
     - 'Inside role2 in task2 role1_library_main - {{ role1_library_main }}'
     - 'Inside role2 in task2 role1_task_vars - {{ role1_task_vars }}'
     - 'Inside role2 in task2 role1_vars_main - {{ role1_vars_main }}'
     - 'Inside role2 in task2 role2_defaults_main - {{ role2_defaults_main }}'
     - 'Inside role2 in task2 role2_vars_main - {{ role2_vars_main }}'
     - 'Inside role2 in task2 role2_library_main - {{ role2_library_main }}'
     - 'Inside role2 in task2 role2_task_vars - {{ role2_task_vars }}'